name: Display Name Script

on:
  push:
    branches:
      - main

jobs:
  display_name:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Run script in Docker
      run: |
        docker run --rm -v $(pwd):/app -w /app ubuntu:latest bash -c '
          echo "My First Name: Anastasiia"
          echo "My Last Name: Lozovan"
        '
